changed all vars, added error to callback
envman/vetus pull request #41
Opened 2018-12-10 16:27 UTC by edkotkas

2018-12-10 16:29 UTC, jmsv requested changes

2018-12-10 16:29 UTC, jmsv commented on example.js
> +let vetus = require('./app')
const?

2018-12-10 16:29 UTC, jmsv commented on app.js
> +let path = require('path')
const?

2018-12-10 16:29 UTC, jmsv commented on app.js
> +let fs = require('fs')
const?

2018-12-10 16:29 UTC, jmsv commented on app.js
> +let Collection = require('./src/collection')
const?

2018-12-10 16:29 UTC, jmsv commented on src/collection.js
> +let path = require('path')
const? for alla these

2018-12-10 16:30 UTC, jmsv commented
`const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const const`

2018-12-10 16:31 UTC, envman commented on src/collection.js
> +        }).catch(callback)
doh

2018-12-10 16:39 UTC, jmsv approved these changes

2018-12-11 11:42 UTC, envman approved these changes

2018-12-11 11:43 UTC, merged